tasks:
  - name: Start all services
    before: |
      git submodule update --recursive --remote
      cd apps/web
    init: |
      pnpm install && turbo run build
    command: |
      pnpm run dev
  - name: Start Strapi
    before: |
      cd apps/cms
    init: |
      pnpm run build
    command: |
      pnpm run develop
  - name: Nav Package
    before: |
      cd packages/navbar
    init: |
      pnpm run build
    command: |
      pnpm run dev
image:
  file: .gitpod.Dockerfile

ports:
  - port: 1337
    visibility: public
    onOpen: ignore
  - port: 3001
    visibility: public
    onOpen: ignore
  - port: 3000
    visibility: public
    onOpen: open-browser
