tasks:
  - name: Start all services
    before: git submodule update --recursive --remote
    init: |
      pnpm install && turbo run build
    command: |
      pnpm run dev

image:
  file: .gitpod.Dockerfile